"""Send a pain point to GitHub or Linear as an issue with its evidence links.

Tokens come from the environment when an issue is sent. Each (root theme, tracker)
gets at most one issue; asking again returns the stored link.
"""
from __future__ import annotations

import os
import sqlite3
from datetime import datetime, timedelta
from typing import Mapping

import httpx

from pulse.config import Config
from pulse.links import jump_link
from pulse.models import to_iso
from pulse.stats import sample_messages, theme_resolution, theme_scores
from pulse.theme_status import status_for

TRACKERS = ("github", "linear")
TRACKER_ENV = {"github": "GITHUB_TOKEN", "linear": "LINEAR_API_KEY"}
TRACKER_LABELS = {"github": "GitHub", "linear": "Linear"}
EVIDENCE_LIMIT = 8
EVIDENCE_DAYS = 30
EXCERPT_CHARS = 200
TIMEOUT = 20.0
_LINEAR_MUTATION = (
    "mutation($input: IssueCreateInput!) { issueCreate(input: $input) { success issue { identifier url } } }"
)


class TrackerError(Exception):
    pass


def target(config: Config, tracker: str) -> str | None:
    return config.integrations.github_repo if tracker == "github" else config.integrations.linear_team_id


def _root(conn: sqlite3.Connection, theme_id: int) -> int:
    root = theme_resolution(conn).get(theme_id)
    if root is None:
        raise LookupError(f"unknown theme {theme_id}")
    return root


def _excerpt(text: str) -> str:
    one = " ".join(text.split()).replace("@", "@​")  # no one on the tracker gets pinged
    return one if len(one) <= EXCERPT_CHARS else one[: EXCERPT_CHARS - 1] + "…"


_MD_SPECIAL = set("`*_{}[]()#+-.!|<>~")


def _md_escape(text: str) -> str:
    """Backslash-escape Markdown syntax characters so untrusted text renders as plain text."""
    return "".join(f"\\{c}" if c in _MD_SPECIAL else c for c in text)


def issue_draft(conn: sqlite3.Connection, theme_id: int, now: datetime) -> dict:
    root = _root(conn, theme_id)
    theme = conn.execute("SELECT name, description FROM themes WHERE id = ?", (root,)).fetchone()
    score = next((s for s in theme_scores(conn, now, limit=1000) if s.theme_id == root), None)
    status = status_for(conn, root)
    sample = sample_messages(conn, now - timedelta(days=EVIDENCE_DAYS), now, theme_id=root, limit=EVIDENCE_LIMIT)
    ids = [m["message_id"] for m in sample]
    where = {}
    if ids:
        where = {r["id"]: r for r in conn.execute(
            f"SELECT id, guild_id, channel_id FROM messages WHERE id IN ({','.join('?' * len(ids))})", ids)}
    lines = ["Reported by the community on Discord. Summary generated by Discord Pulse.", ""]
    if theme["description"]:
        lines += [_md_escape(theme["description"]), ""]
    if score is not None:
        lines += [
            f"- Messages in the last 7 days: {score.volume} (previous 7 days: {score.prev_volume})",
            f"- Average negativity: {score.mean_negativity:.1f} of 2",
        ]
    note = _md_escape(status["note"]) if status["note"] else ""
    lines.append(f"- Status: {status['label']}" + (f" ({note})" if note else ""))
    if sample:
        lines += ["", "### Example messages", ""]
        for m in sample:
            r = where[m["message_id"]]
            link = jump_link(r["guild_id"], r["channel_id"], m["message_id"])
            lines.append(f"- {_md_escape(_excerpt(m['content']))} ([open in Discord]({link}))")
    return {"theme_id": root, "title": f"Community pain point: {theme['name']}", "body": "\n".join(lines)}


def existing_issue(conn: sqlite3.Connection, theme_id: int, tracker: str) -> dict | None:
    row = conn.execute(
        "SELECT url, identifier FROM theme_issues WHERE theme_id = ? AND tracker = ?",
        (_root(conn, theme_id), tracker),
    ).fetchone()
    return {"url": row["url"], "identifier": row["identifier"]} if row else None


def tracker_status(conn, config: Config, theme_id: int, env: Mapping[str, str] | None = None) -> list[dict]:
    env = os.environ if env is None else env
    out = []
    for tracker in TRACKERS:
        tgt = target(config, tracker)
        if not tgt:
            continue
        ready = bool(env.get(TRACKER_ENV[tracker]))
        out.append({
            "tracker": tracker, "label": TRACKER_LABELS[tracker], "target": tgt,
            "existing": existing_issue(conn, theme_id, tracker), "ready": ready,
            "reason": None if ready else f"Set {TRACKER_ENV[tracker]} to send issues to {TRACKER_LABELS[tracker]}",
        })
    return out


def _post(client: httpx.Client, name: str, url: str, **kwargs) -> httpx.Response:
    try:
        return client.post(url, timeout=TIMEOUT, **kwargs)
    except httpx.HTTPError as e:
        raise TrackerError(f"could not reach {name}: {e}") from e


def create_github_issue(client, repo, token, title, body, labels) -> tuple[str, str]:
    r = _post(client, "GitHub", f"https://api.github.com/repos/{repo}/issues",
              headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json",
                       "X-GitHub-Api-Version": "2022-11-28"},
              json={"title": title, "body": body, "labels": list(labels)})
    if r.status_code >= 400:
        try:
            detail = r.json().get("message", r.text[:200])
        except ValueError:
            detail = r.text[:200]
        raise TrackerError(f"GitHub returned {r.status_code}: {detail}")
    try:
        data = r.json()
        return data["html_url"], f"#{data['number']}"
    except (ValueError, KeyError, TypeError) as e:
        raise TrackerError("GitHub returned an unexpected response") from e


def create_linear_issue(client, team_id, token, title, body) -> tuple[str, str]:
    r = _post(client, "Linear", "https://api.linear.app/graphql",
              headers={"Authorization": token, "Content-Type": "application/json"},
              json={"query": _LINEAR_MUTATION,
                    "variables": {"input": {"teamId": team_id, "title": title, "description": body}}})
    if r.status_code >= 400:
        raise TrackerError(f"Linear returned {r.status_code}: {r.text[:200]}")
    try:
        data = r.json()
        if data.get("errors"):
            raise TrackerError("Linear: " + "; ".join(str(e.get("message")) for e in data["errors"]))
        created = (data.get("data") or {}).get("issueCreate") or {}
        if not created.get("success"):
            raise TrackerError("Linear did not create the issue")
        return created["issue"]["url"], created["issue"]["identifier"]
    except (ValueError, KeyError, TypeError) as e:
        raise TrackerError("Linear returned an unexpected response") from e


def send_issue(conn, config: Config, theme_id: int, tracker: str, now: datetime, *,
               client: httpx.Client | None = None, env: Mapping[str, str] | None = None) -> dict:
    if tracker not in TRACKERS:
        raise ValueError(f"unknown tracker {tracker!r}; use one of {list(TRACKERS)}")
    tgt = target(config, tracker)
    if not tgt:
        raise TrackerError(f"{TRACKER_LABELS[tracker]} is not set up: add [integrations.{tracker}] to pulse.toml")
    draft = issue_draft(conn, theme_id, now)
    existing = existing_issue(conn, draft["theme_id"], tracker)
    if existing is not None:
        return {**existing, "created": False}
    env = os.environ if env is None else env
    token = env.get(TRACKER_ENV[tracker])
    if not token:
        raise TrackerError(f"{TRACKER_ENV[tracker]} must be set to send issues to {TRACKER_LABELS[tracker]}")
    own = client is None
    client = client or httpx.Client()
    try:
        if tracker == "github":
            url, ident = create_github_issue(client, tgt, token, draft["title"], draft["body"],
                                             config.integrations.github_labels)
        else:
            url, ident = create_linear_issue(client, tgt, token, draft["title"], draft["body"])
    finally:
        if own:
            client.close()
    with conn:
        conn.execute(
            "INSERT OR IGNORE INTO theme_issues (theme_id, tracker, url, identifier, created_at)"
            " VALUES (?, ?, ?, ?, ?)",
            (draft["theme_id"], tracker, url, ident, to_iso(now)),
        )
        stored = conn.execute(
            "SELECT url, identifier FROM theme_issues WHERE theme_id = ? AND tracker = ?",
            (draft["theme_id"], tracker),
        ).fetchone()
    return {"url": stored["url"], "identifier": stored["identifier"], "created": stored["url"] == url}
